CREATE DATABASE `PROJECT` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'PROJECT'@'localhost' IDENTIFIED BY 'PASSWORD1';
GRANT INSERT,SELECT,UPDATE ON libellum . * TO 'libellum'@'localhost';
CREATE USER 'PROJECT_cmdline'@'localhost' IDENTIFIED BY 'PASSOWRD2';
GRANT CREATE,DROP,DELETE,INSERT,SELECT,UPDATE ON libellum . * TO 'PROJECT_cmdline'@'localhost';